### ISSUE TITLE
Send exceptions to a monitoring service

### ISSUE THREAD

**Issue by tobias** [ato/clojars-web#351]
Such as http://yellerapp.com/ or similar.

**Comment by danielcompton** [comment]
@yellerapp is free for open source/academic work, I've asked @tcrayford about this and he'll chime in in a bit.

**Comment by tcrayford** [comment]
Looks like clojars has been sending Yeller exceptions, but I don't see the code for that in this repo. Let me know if I can do anything for you @tobias - clojars has been great to me, and I'm happy to help in any way I can.

**Comment by tobias** [comment]
@tcrayford - I have a stash locally that reports to Yeller, I just need to clean it up and figure out where we want to manually report exceptions. I created this issue as a reminder to do just that at some point :) I'll see if I can get that pushed at least as a branch today.

**Comment by tobias** [comment]
@tcrayford - I have yeller support sitting on a branch (see above), but can't seem to make it work - exceptions that get passed to https://github.com/ato/clojars-web/tree/yeller-support/src/clojars/error_reporting.clj#L20 don't seem to make it to yeller. If I manually create a client from the repl with the same settings, it works. Would you be willing to take a look and see if there's something obvious I'm doing wrong?

You can pull the `yeller-support` branch, then:

```
export YELLER_TOKEN=<token>
lein run
curl localhost:8080/error
```

That should report an error to the `development` environment of the yeller account, but doesn't.

**Comment by tcrayford** [comment]
@tobias Ack. That's because Yeller by default *ignores* exceptions sent in `development` or `test` environments - see https://github.com/yeller/yeller_java/blob/master/src/com/yellerapp/client/Reporter.java#L32 (the yeller clojure client is just a very thin wrapper around the java client).

This is on purpose - it means you can just call the client in your dev or test environments, without sending errors to Yeller (which you probably don't want anyway - usually devs make a tonne of errors whilst doing their work, and mixing that in with production errors can be real confusing).

So to fix it locally:

```bash
export YELLER_TOKEN=<token>
export YELLER_ENV=production
lein run
curl localhost:8080/error
```

I tested that myself and it works properly.

**Comment by tobias** [comment]
Ah, that makes perfect sense. Thanks for taking a look.
