### ISSUE TITLE
https://clojars.org/org.clojure/core.async appears broken

### ISSUE THREAD

**Issue by LoginError** [ato/clojars-web#358]
Searching for [org.clojure/core.async](https://clojars.org/search?q=org.clojure%2Fcore.async) shows a result with the latest version being `0.1.361.0-d8047c-alpha` corresponding to clojure/core.async@d8047c0b0ec13788c1092f579f03733ee635c493

Attempting to access it in the browser gives me:
**Page not found
Thundering typhoons! I think we lost it. Sorry!**

I am likewise unable to access it via leinengen:
in `project.clj` : ` [org.clojure/core.async "0.1.338.0-5c5012-alpha"]`
and running `lein deps` yeilds:
```
Could not find artifact org.clojure:core.async:jar:0.1.361.0-d8047c-alpha in clojars 
(https://clojars.org/repo/)
````

**Comment by danielcompton** [comment]
core.async (and all Clojure Core) is released to Maven central, so I wouldn't expect to find it in Clojars.

**Comment by tobias** [comment]
As @danielcompton said, all `org.clojure` projects are published to
central, you can see them here:
https://search.maven.org/#search|ga|1|g%3A"org.clojure"%20AND%20a%3A"core.async". Central
is in lein's default repo list, so it should pull from there.

`org.clojure/core-async` shows up in the search results because
someone pushed a fork under a different group name, but did not change
the group name in the pom file. The search indexes the pom files, and
disregards the path name the artifact is stored under, but then we
assume that the groupId/artifactId from the search result is the
correct path to the artifact in the repo, which leads to the 404 in
this case.

To prevent this from happening in the future, we could reject
deployments where the info in the pom does not match the deployment
path (#359). We can also not add non-existent paths to the search
index (#360).
