### ISSUE TITLE
Proposal: Deprecate projects.

### ISSUE THREAD

**Issue by thiagofm** [ato/clojars-web#366]
Hello,

I'm looking for ways to contribute with the project, so one that I've thought it was going to be easy to start  is adding more features.

I've seen people asking for it in #284.

My idea is to add an [x] button close to the listed projects of a person in their dashboard with the option to deprecate it. Maybe we can go further with the design later.

To deprecate, we can add a flag to the database so we don't remove them completely and still let the user see the projects it deprecated(and maybe publish them again).

Obviously, deprecated projects will not be seem by default when searching and this will need some work too.

What do you think @tobias ?

**Comment by tobias** [comment]
Welcome @thiagofm! Thanks for helping out.

I'm not convinced having a button on the UI for deprecating a project
is a good way to handle deprecation, primarily because it now leads to
two ways to deprecate: via the UI, and via the pom description. And as
soon as we add a deprecated flag, users will ask us to expose it in
the API, then someone will build tooling around it, which would miss
all the projects that were deprecated via the pom description.

I'm happy to leave this issue open though, in case anyone wants to
make a compelling case for this feature.

I really appreciate you giving this issue consideration, and please
don't let my response discourage you from contributing on other
issues.

**Comment by thiagofm** [comment]
Don't worry, I'll find something else in the project to work on then. You are right, It makes sense to have only one way to deprecate things.
