### ISSUE TITLE
Deletion request

### ISSUE THREAD

**Issue by totakke** [ato/clojars-web#368]
I've pushed jar signed with wrong key.

https://clojars.org/cljam/versions/0.1.3

Please delete only v0.1.3.

**Comment by tobias** [comment]
I'd prefer to not delete this just for being signed with the wrong key, since that won't affect usage. And deleting that version would allow reuploading it with possibly different contents, which could lead to surprising and hard to debug issues for users. The proper solution would be to upload a new version signed with the correct key.

**Comment by totakke** [comment]
I got it. Thanks.
