### ISSUE TITLE
Checksum validation failed during deploy

### ISSUE THREAD

**Issue by postspectacular** [ato/clojars-web#369]
```
lein deploy clojars
Wrote ..../literate-template/pom.xml
Created ..../literate-template/target/lein-template-0.3.0.jar

You need a passphrase to unlock the secret key for
user: "......."
4096-bit RSA key, ID 1960829A, created 2014-02-15

You need a passphrase to unlock the secret key for
user: "......."
4096-bit RSA key, ID 1960829A, created 2014-02-15

Sending thing-babel/lein-template/0.3.0/lein-template-0.3.0.pom (3k)
    to https://clojars.org/repo/
Sending thing-babel/lein-template/0.3.0/lein-template-0.3.0.jar (13k)
    to https://clojars.org/repo/
Sending thing-babel/lein-template/0.3.0/lein-template-0.3.0.jar.asc (1k)
    to https://clojars.org/repo/
Sending thing-babel/lein-template/0.3.0/lein-template-0.3.0.pom.asc (1k)
    to https://clojars.org/repo/
Retrieving thing-babel/lein-template/maven-metadata.xml (1k)
    from https://clojars.org/repo/
Checksum validation failed, expected e861d0504085f52b1737f08d9083b65d3374ad1b but is a8ab41645c3a172f798e0b943aba0cec491d09f2
Retrieving thing-babel/lein-template/maven-metadata.xml (1k)
    from https://clojars.org/repo/
Could not transfer metadata thing-babel:lein-template/maven-metadata.xml from/to clojars (https://clojars.org/repo/): Checksum validation failed, expected e861d0504085f52b1737f08d9083b65d3374ad1b but is a8ab41645c3a172f798e0b943aba0cec491d09f2
Failed to retrieve remote metadata thing-babel:lein-template/maven-metadata.xml: Could not transfer metadata thing-babel:lein-template/maven-metadata.xml from/to clojars (https://clojars.org/repo/): Checksum validation failed, expected e861d0504085f52b1737f08d9083b65d3374ad1b but is a8ab41645c3a172f798e0b943aba0cec491d09f2
```

I've been having issues w/ this specific project repo for a while, but hoped another version change would have helped by now...

In fact, https://clojars.org/repo/thing-babel/lein-template/ shows that `maven-metadata.xml` hasn't been updated on the server since 2014-03-15, 4 versions behind...

What is the best way to reset this seemingly corrupted file? In the past, I sent Phil a GPG signed deletion request (for another project) - is that still the desired approach? Who is the new main contact for such issues?

Thanks!

**Comment by tobias** [comment]
That error means that the checksum stored on the server isn't correct,
and the aether client is rejecting the maven-metadata.xml as corrupt,
since the data it downloaded doesn't match the downloaded
checksum. The checksums can get out of sync in the case of a partial
deploy - the maven-metadata.xml gets uploaded, but the network hiccups
when uploading the checksum file, and the old checksum isn't
overridden. Once it gets in that state, the only fix is to manually
update the metadata and checksums, which I have done -
maven-metadata.xml now lists all of the releases, and has correct
checksums. You confirm it now works for you by deploying a SNAPSHOT if
you are willing to do so.

Once we implement #226 (atomic deploys), this sort of thing shouldn't
happen again, since we'll confirm the checksums before accepting the
deploy, but until then, it can still happen.

I'm now the primary contact for clojars issues, so if you need
something, please file an issue here, or email contact@clojars.org if
it's a sensitive issue and we can go from there.

**Comment by tobias** [comment]
@postspectacular - can you confirm that you can now deploy a snapshot?

**Comment by postspectacular** [comment]
Hi @tobias - yes, thanks - just done! Is it also safe to try another release deploy (w/ new version)?

**Comment by tobias** [comment]
@postspectacular yep, you should be able to do a versioned release. If it fails, let me know.

**Comment by postspectacular** [comment]
@tobias thanks, done - all good!

**Comment by tobias** [comment]
My pleasure!
